{
  "jobs": [
    {
      "id": 1,
      "job_name": "SampleJob1",
      "wait_time": 5,
      "completion_wait": 10,
      "parameter_sets": [
        {
          "param1": "value1"
        }
      ]
    },
    {
      "id": 2,
      "job_name": "SampleJob2",
      "wait_time": 5,
      "completion_wait": 10,
      "parameter_sets": [
        {
          "param1": "value2"
        }
      ]
    },
    {
      "id": 3,
      "job_name": "SampleJob3",
      "wait_time": 5,
      "completion_wait": 10,
      "parameter_sets": [
        {
          "param1": "value3"
        }
      ]
    }
  ]
}
