name: Trigger Jenkins Jobs with String Parameter

on:
  push:
    branches:
      - main

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read JSON file
        id: read_json
        run: |
          echo "PARAMS=$(jq -c . .github/params/params.json)" >> $GITHUB_ENV

      - name: Trigger Jenkins Jobs
        run: |
          for job in $(echo $PARAMS | jq -r 'keys[]'); do
            param=$(echo $PARAMS | jq -c ".\"$job\"")
            echo "Triggering Jenkins job: $job with parameter: $param"
            
            # Extract the specific parameter dynamically
            stringParam=$(echo $param | jq -r 'to_entries | map("\(.key)=\(.value)") | .[]')
            
            # Trigger the Jenkins job
            curl -X POST "https://b238-103-215-237-138.ngrok-free.app/job/$job/buildWithParameters" \
              --user "${{ secrets.JENKINS_USERNAME }}:${{ secrets.JENKINS_TOKEN }}" \
              --data-urlencode "$stringParam"
          done
